# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fGZSPA7ggcf0ldNZHkYhChDpEf2RckK-
"""

# Устанавливаем необходимые библиотеки (только если их нет)
!pip install -q transformers datasets peft accelerate evaluate trl bitsandbytes triton

# Импортируем библиотеки
import torch
import numpy as np
import time
import gc
from datasets import load_dataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    TrainingArguments,
    Trainer,
    DataCollatorForLanguageModeling,
)
from peft import LoraConfig, get_peft_model, TaskType
from huggingface_hub import login
from google.colab import userdata
import evaluate
from tqdm import tqdm

# Аутентификация на Hugging Face (токен хранится в секретах Colab)
hf_token = userdata.get('HF_TOKEN')
login(token=hf_token)

# Загружаем датасет
dataset = load_dataset("phatvo/hotpotqa-raft-1k", split="train")
print("Колонки датасета:", dataset.column_names)
# Вывод: ['id', 'type', 'question', 'context', 'oracle_context', 'cot_answer', 'instruction', 'text']

# Посмотрим первый пример, чтобы понять структуру
print(dataset[0])

# Фиксируем seed для воспроизводимости
np.random.seed(42)
indices = np.random.permutation(len(dataset))
train_indices = indices[:80]   # первые 80 для обучения
test_indices = indices[80:100] # следующие 20 для тестирования

train_dataset = dataset.select(train_indices)
test_dataset = dataset.select(test_indices)

print(f"Размер обучающей выборки: {len(train_dataset)}")
print(f"Размер тестовой выборки: {len(test_dataset)}")

model_name = "Qwen/Qwen2.5-0.5B-Instruct"
tokenizer = AutoTokenizer.from_pretrained(model_name)

# Устанавливаем pad_token = eos_token, чтобы избежать предупреждений
tokenizer.pad_token = tokenizer.eos_token

# Загружаем модель в bfloat16 для экономии памяти
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.bfloat16,
    device_map="auto"
)

# Проверяем, что модель загрузилась на GPU
print("Устройство:", model.device)

# Конфигурация LoRA: rank=8, alpha=32, dropout=0.1
# Целевые модули для Qwen (q_proj, k_proj, v_proj, o_proj)
lora_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    r=8,
    lora_alpha=32,
    lora_dropout=0.1,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"]
)

# Применяем LoRA к модели
# Примечание: предупреждение про отсутствующий triton можно игнорировать,
# оно влияет только на максимальную скорость вычислений, но не на логику работы.
model = get_peft_model(model, lora_config)
model.print_trainable_parameters()
# Выведет количество обучаемых параметров (в миллионах)

def format_training_example(example):
    """Форматирует пример для обучения: user = Context + Question, assistant = cot_answer"""
    user_content = f"Context:\n{example['context']}\n\nQuestion: {example['question']}"
    messages = [
        {"role": "user", "content": user_content},
        {"role": "assistant", "content": example['cot_answer']}
    ]
    # add_generation_prompt=False, так как мы включаем ответ ассистента
    prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=False)
    return {"text": prompt}

def format_inference_example(example):
    """Форматирует пример для инференса: только user, с generation prompt"""
    user_content = f"Context:\n{example['context']}\n\nQuestion: {example['question']}"
    messages = [{"role": "user", "content": user_content}]
    prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    return {"prompt": prompt}

# Применяем форматирование
train_dataset = train_dataset.map(format_training_example)
test_dataset_raw = test_dataset.map(format_inference_example)  # для инференса
# Для оценки перплексии нам нужен будет тестовый датасет в формате как для обучения
test_dataset_eval = test_dataset.map(format_training_example)

def tokenize_function(examples):
    """Токенизирует текст и создает метки (labels = input_ids)"""
    tokenized = tokenizer(
        examples["text"],
        truncation=True,
        padding="max_length",
        max_length=1024,          # может потребоваться увеличить, если контексты длинные
        return_tensors=None
    )
    tokenized["labels"] = tokenized["input_ids"].copy()
    return tokenized

# Токенизируем обучающий и оценочный (для перплексии) датасеты
train_tokenized = train_dataset.map(tokenize_function, batched=True, remove_columns=train_dataset.column_names)
test_tokenized = test_dataset_eval.map(tokenize_function, batched=True, remove_columns=test_dataset_eval.column_names)

# Аргументы обучения
training_args = TrainingArguments(
    output_dir="./qwen-raft-lora",
    per_device_train_batch_size=2,      # небольшой batch для Colab
    per_device_eval_batch_size=2,
    num_train_epochs=2,
    logging_steps=10,
    save_steps=100,
    eval_strategy="steps",               # будем оценивать на test после каждой эпохи
    eval_steps=100,
    save_total_limit=1,
    learning_rate=2e-5,
    bf16=True,                           # используем bfloat16
    fp16=False,
    push_to_hub=False,
    report_to="none",
    gradient_accumulation_steps=2,       # имитируем batch=4
)

# Коллатор данных (языковое моделирование)
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

# Инициализируем Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_tokenized,
    eval_dataset=test_tokenized,        # будем вычислять loss на тесте во время обучения
    data_collator=data_collator,
    processing_class=tokenizer,         # обновлено: в новых версиях используется processing_class вместо tokenizer
)

# Очищаем кэш GPU перед началом
torch.cuda.reset_peak_memory_stats()

# Засекаем время
start_time = time.time()

# Запускаем обучение
trainer.train()

# Время окончания
end_time = time.time()
training_time_min = (end_time - start_time) / 60
print(f"Время обучения: {training_time_min:.2f} мин")

# Получаем максимальную выделенную память в байтах и переводим в ГБ
peak_memory_bytes = torch.cuda.max_memory_allocated()
peak_memory_gb = peak_memory_bytes / (1024 ** 3)
print(f"Пиковое использование GPU памяти: {peak_memory_gb:.2f} ГБ")

trainable_params = model.num_parameters(only_trainable=True) / 1e6
print(f"Обучаемые параметры: {trainable_params:.2f} млн")

# После обучения вычисляем loss на тестовом датасете
eval_results = trainer.evaluate(test_tokenized)
eval_loss = eval_results["eval_loss"]
perplexity = np.exp(eval_loss)
print(f"Perplexity на тесте: {perplexity:.4f}")

# Переводим модель в режим оценки
model.eval()

def compute_f1(pred, truth):
    """Вычисляет F1 на уровне слов (разбиение по пробелам)"""
    pred_tokens = pred.split()
    truth_tokens = truth.split()
    common = set(pred_tokens) & set(truth_tokens)
    if not common:
        return 0.0
    precision = len(common) / len(pred_tokens)
    recall = len(common) / len(truth_tokens)
    f1 = 2 * precision * recall / (precision + recall)
    return f1

predictions = []
references = []

# Генерируем ответы для каждого тестового примера
for example in tqdm(test_dataset_raw, desc="Генерация ответов"):
    input_ids = tokenizer.encode(example["prompt"], return_tensors="pt").to(model.device)
    with torch.no_grad():
        outputs = model.generate(
            input_ids,
            max_new_tokens=128,
            do_sample=False,              # жадная декодировка
            pad_token_id=tokenizer.eos_token_id
        )
    generated = tokenizer.decode(outputs[0][input_ids.shape[1]:], skip_special_tokens=True)
    predictions.append(generated)
    references.append(example["cot_answer"])   # используем cot_answer как эталон

# Вычисляем F1 и Exact Match
f1_scores = []
exact_matches = []
for pred, ref in zip(predictions, references):
    f1 = compute_f1(pred, ref)
    f1_scores.append(f1)
    exact_matches.append(1 if pred.strip() == ref.strip() else 0)

avg_f1 = np.mean(f1_scores)
em = np.mean(exact_matches)
print(f"Средний F1: {avg_f1:.4f}")
print(f"Exact Match: {em:.4f}")

print("\n=== Результаты эксперимента ===")
print(f"Модель: {model_name} + LoRA")
print(f"Обучаемые параметры: {trainable_params:.2f} млн")
print(f"Время обучения: {training_time_min:.2f} мин")
print(f"Пиковое использование GPU памяти: {peak_memory_gb:.2f} ГБ")
print(f"Perplexity на тесте: {perplexity:.4f}")
print(f"F1 на тесте: {avg_f1:.4f}")

