{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "gpuType": "T4",
      "authorship_tag": "ABX9TyMQPsGIn+XT3HEK+m3ynEpt",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    },
    "accelerator": "GPU"
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/TimofeyProtasov/diploma/blob/main/days/work_1604%2B.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "!pip install -q triton trl"
      ],
      "metadata": {
        "id": "zmV0JShKeLu6"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "IN8ararQ1pmr"
      },
      "outputs": [],
      "source": [
        "import torch\n",
        "import random\n",
        "from typing import Optional\n",
        "from sklearn.model_selection import train_test_split\n",
        "from dataclasses import dataclass, field\n",
        "from datasets import load_dataset, Dataset, DatasetDict\n",
        "from trl import SFTTrainer, SFTConfig\n",
        "from transformers import (\n",
        "    AutoTokenizer,\n",
        "    AutoModelForCausalLM\n",
        ")\n",
        "from peft import (\n",
        "    LoraConfig,\n",
        "    get_peft_model,\n",
        "    TaskType,\n",
        "    PeftConfig\n",
        ")"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "@dataclass\n",
        "class RAGExperiment:\n",
        "    dataset_name: str = 'phatvo/hotpotqa-raft'\n",
        "    oracle_presence_ratio: float = 1.0\n",
        "    sample_size: int = 10\n",
        "    test_size_ratio: float = 0.2\n",
        "    model_name: str = 'Qwen/Qwen2.5-0.5B-Instruct'\n",
        "    peft_config: Optional[PeftConfig] = field(default_factory=lambda: LoraConfig(\n",
        "        r=8,\n",
        "        lora_alpha=16,\n",
        "        target_modules=[\"q_proj\", \"v_proj\"],\n",
        "        lora_dropout=0.1,\n",
        "        bias=\"none\",\n",
        "        task_type=TaskType.CAUSAL_LM,\n",
        "    ))\n",
        "    num_train_epochs: int = 3\n",
        "    per_device_train_batch_size: int = 2\n",
        "    gradient_accumulation_steps: int = 2\n",
        "    learning_rate: float = 5e-5\n",
        "    warmup_steps: int = 5\n",
        "    seed: int = 1\n",
        "\n",
        "\n",
        "    def __post_init__(self):\n",
        "        random.seed(self.seed)\n",
        "\n",
        "\n",
        "    def prepare_data(self):\n",
        "        dataset: DatasetDict = load_dataset('phatvo/hotpotqa-raft')\n",
        "\n",
        "\n",
        "        def presence_oracle(example):\n",
        "            return example['oracle_context'] in example['instruction']\n",
        "\n",
        "\n",
        "        dataset_with_oracle: Dataset = dataset['train'].filter(lambda ex: presence_oracle(ex))\n",
        "        dataset_without_oracle: Dataset = dataset['train'].filter(lambda ex: not presence_oracle(ex))\n",
        "\n",
        "        num_with: int = round(self.sample_size * self.oracle_presence_ratio)\n",
        "        num_without: int = self.sample_size - num_with\n",
        "\n",
        "        indices_with: list = random.sample(range(len(dataset_with_oracle)), num_with)\n",
        "        indices_without: list = random.sample(range(len(dataset_without_oracle)), num_without)\n",
        "\n",
        "        idx_train_with_oracle, idx_test_with_oracle = train_test_split(\n",
        "            indices_with,\n",
        "            test_size=self.test_size_ratio,\n",
        "            shuffle=False,\n",
        "            random_state=self.seed\n",
        "        )\n",
        "\n",
        "        idx_train_without_oracle, idx_test_without_oracle = train_test_split(\n",
        "            indices_without,\n",
        "            test_size=self.test_size_ratio,\n",
        "            shuffle=False,\n",
        "            random_state=self.seed\n",
        "        )\n",
        "\n",
        "        def get_shuffle_dataset(indices_with, indices_without):\n",
        "            return concatenate_datasets([\n",
        "                dataset_with_oracle.select(indices_with),\n",
        "                dataset_without_oracle.select(indices_without)\n",
        "            ]).shuffle(seed=self.seed)\n",
        "\n",
        "\n",
        "        self.train_dataset: Dataset = get_shuffle_dataset(idx_train_with_oracle, idx_train_without_oracle)\n",
        "        self.test_dataset: Dataset = get_shuffle_dataset(idx_test_with_oracle, idx_test_without_oracle)\n",
        "\n",
        "\n",
        "    def prepare_model(self):\n",
        "        self.model = AutoModelForCausalLM.from_pretrained(\n",
        "            self.model_name,\n",
        "            dtype=torch.bfloat16,\n",
        "            device_map='auto'\n",
        "        )\n",
        "\n",
        "\n",
        "    def prepare_tokenizer(self):\n",
        "        self.tokenizer = AutoTokenizer.from_pretrained(\n",
        "            self.model_name\n",
        "        )\n",
        "\n",
        "\n",
        "    def format_data(self):\n",
        "        def format_train_example(example):\n",
        "            messages = [\n",
        "                {\"role\": \"user\", \"content\": example[\"instruction\"]},\n",
        "                {\"role\": \"assistant\", \"content\": example[\"cot_answer\"]}\n",
        "            ]\n",
        "            formatted = self.tokenizer.apply_chat_template(\n",
        "                messages,\n",
        "                tokenize=False,\n",
        "                add_generation_prompt=False\n",
        "            )\n",
        "            return {'formatted_text': formatted}\n",
        "\n",
        "\n",
        "        def format_inference_example(example):\n",
        "            messages = [\n",
        "                {\"role\": \"user\", \"content\": example[\"instruction\"]}\n",
        "            ]\n",
        "            formatted = self.tokenizer.apply_chat_template(\n",
        "                messages,\n",
        "                tokenize=False,\n",
        "                add_generation_prompt=True\n",
        "            )\n",
        "            return {'formatted_text': formatted}\n",
        "\n",
        "        self.formatted_train_dataset = self.train_dataset.map(format_train_example)\n",
        "        self.formatted_test_dataset = self.test_dataset.map(format_inference_example)\n",
        "        self.formatted_eval_dataset = self.test_dataset.map(format_train_example)\n",
        "\n",
        "\n",
        "    def tokenize(self):\n",
        "        def tokenize_function(examples):\n",
        "            return self.tokenizer(\n",
        "                examples['formatted_text'],\n",
        "                truncation=True,\n",
        "                truncation_side='left',\n",
        "                max_length=1024,\n",
        "                padding=False,\n",
        "                return_tensors=None,\n",
        "            )\n",
        "\n",
        "        self.tokenized_train_dataset = self.formatted_train_dataset.map(\n",
        "            tokenize_function,\n",
        "            batched=True,\n",
        "            remove_columns=self.formatted_train_dataset.column_names,\n",
        "        )\n",
        "\n",
        "        self.tokenized_test_dataset = self.formatted_test_dataset.map(\n",
        "            tokenize_function,\n",
        "            batched=True,\n",
        "            remove_columns=self.formatted_test_dataset.column_names,\n",
        "        )\n",
        "\n",
        "        self.tokenized_eval_dataset = self.formatted_eval_dataset.map(\n",
        "            tokenize_function,\n",
        "            batched=True,\n",
        "            remove_columns=self.formatted_eval_dataset.column_names,\n",
        "        )\n",
        "\n",
        "\n",
        "    def add_peft_if_exist(self):\n",
        "        self.model = get_peft_model(self.model, self.peft_config) if self.peft_config else self.model\n",
        "\n",
        "\n",
        "    def prepare_training(self):\n",
        "        self.training_args = SFTConfig(\n",
        "            output_dir=\"./qwen-raft-lora\",\n",
        "            num_train_epochs=self.num_train_epochs,\n",
        "            per_device_train_batch_size=self.per_device_train_batch_size,\n",
        "            gradient_accumulation_steps=self.gradient_accumulation_steps,\n",
        "            learning_rate=self.learning_rate,\n",
        "            warmup_steps=self.warmup_steps,\n",
        "            logging_steps=10,\n",
        "            save_steps=100,\n",
        "            save_total_limit=2,\n",
        "            fp16=True,\n",
        "            report_to=\"none\",\n",
        "            remove_unused_columns=False,\n",
        "        )\n",
        "\n",
        "        self.trainer = SFTTrainer(\n",
        "            model=self.model,\n",
        "            args=self.training_args,\n",
        "            train_dataset=self.tokenized_train_dataset,\n",
        "            tokenizer=self.tokenizer,\n",
        "            completion_only_loss=True,\n",
        "            response_template=\"<|im_start|>assistant\",\n",
        "        )\n",
        "\n",
        "\n",
        "    def train(self):\n",
        "        self.trainer.train()\n",
        "\n",
        "\n",
        "    def evaluate_perplexity(self):\n",
        "        pass\n",
        "\n",
        "\n",
        "    def evaluate_f1(self):\n",
        "        pass\n",
        "\n",
        "\n",
        "    def run(self):\n",
        "        self.prepare_data()\n",
        "        self.prepare_model()\n",
        "        self.prepare_tokenizer()\n",
        "        self.format_data()\n",
        "        self.tokenize()\n",
        "        self.add_peft_if_exist()\n",
        "        self.prepare_training()\n",
        "        self.train()\n",
        "        self.evaluate_perplexity()\n",
        "        self.evaluate_f1()"
      ],
      "metadata": {
        "id": "Fv8gEo7f37zc"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "exp = RAGExperiment(\n",
        "    dataset_name='phatvo/hotpotqa-raft',\n",
        "    oracle_presence_ratio=1.0,\n",
        "    sample_size=10,\n",
        "    test_size_ratio=0.2,\n",
        "    model_name='Qwen/Qwen2.5-0.5B-Instruct',\n",
        "    LoraConfig(\n",
        "        r=8,\n",
        "        lora_alpha=16,\n",
        "        target_modules=[\"q_proj\", \"v_proj\"],\n",
        "        lora_dropout=0.1,\n",
        "        bias=\"none\",\n",
        "        task_type=TaskType.CAUSAL_LM,\n",
        "    ),\n",
        "    num_train_epochs=3,\n",
        "    per_device_train_batch_size=2,\n",
        "    gradient_accumulation_steps=2,\n",
        "    learning_rate=5e-5,\n",
        "    warmup_steps=5,\n",
        "    seed=1,\n",
        ")"
      ],
      "metadata": {
        "id": "6uAE4kwg10wN"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "# Установка (при необходимости)\n",
        "# !pip install -U transformers datasets accelerate peft trl torch\n",
        "\n",
        "import torch\n",
        "from transformers import AutoModelForCausalLM, AutoTokenizer\n",
        "from datasets import Dataset\n",
        "from trl import SFTTrainer, SFTConfig\n",
        "\n",
        "# ------------------------------------------------------------\n",
        "# 1. Загружаем модель и токенизатор\n",
        "# ------------------------------------------------------------\n",
        "model_name = \"Qwen/Qwen2.5-0.5B-Instruct\"\n",
        "tokenizer = AutoTokenizer.from_pretrained(model_name)\n",
        "tokenizer.padding_side = \"right\"\n",
        "\n",
        "if tokenizer.pad_token is None:\n",
        "    tokenizer.pad_token = tokenizer.eos_token\n",
        "\n",
        "model = AutoModelForCausalLM.from_pretrained(\n",
        "    model_name,\n",
        "    torch_dtype=torch.bfloat16,\n",
        "    device_map=\"auto\",\n",
        ")\n",
        "\n",
        "# ------------------------------------------------------------\n",
        "# 2. Создаём тестовый датасет (сырой текст)\n",
        "# ------------------------------------------------------------\n",
        "def create_conversation(instruction, answer):\n",
        "    messages = [\n",
        "        {\"role\": \"user\", \"content\": instruction},\n",
        "        {\"role\": \"assistant\", \"content\": answer},\n",
        "    ]\n",
        "    return tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=False)\n",
        "\n",
        "examples = [\n",
        "    create_conversation(\"Как дела?\", \"Всё отлично, спасибо!\"),\n",
        "    create_conversation(\"Сколько будет 2+2?\", \"2+2 равно 4.\"),\n",
        "]\n",
        "\n",
        "raw_dataset = Dataset.from_dict({\"text\": examples})\n",
        "\n",
        "# Токенизируем (как у вас в классе)\n",
        "def tokenize_function(examples):\n",
        "    return tokenizer(\n",
        "        examples[\"text\"],\n",
        "        truncation=True,\n",
        "        max_length=1024,\n",
        "        padding=False,\n",
        "    )\n",
        "\n",
        "tokenized_dataset = raw_dataset.map(tokenize_function, batched=True)\n",
        "\n",
        "# ------------------------------------------------------------\n",
        "# 3. Настраиваем SFTConfig и SFTTrainer (исправлено под trl >= 0.20)\n",
        "# ------------------------------------------------------------\n",
        "training_args = SFTConfig(\n",
        "    output_dir=\"./test-sft\",\n",
        "    per_device_train_batch_size=2,\n",
        "    report_to=\"none\",\n",
        "    max_seq_length=1024,                      # ← теперь здесь\n",
        "    # Параметры маскирования промпта:\n",
        "    completion_only_loss=True,\n",
        "    response_template=\"<|im_start|>assistant\",\n",
        "    # Явно указываем, что датасет уже токенизирован\n",
        "    dataset_text_field=None,\n",
        ")\n",
        "\n",
        "trainer = SFTTrainer(\n",
        "    model=model,\n",
        "    args=training_args,\n",
        "    train_dataset=tokenized_dataset,\n",
        "    processing_class=tokenizer,               # для trl >= 0.20\n",
        ")\n",
        "\n",
        "# ------------------------------------------------------------\n",
        "# 4. Получаем батч и анализируем labels\n",
        "# ------------------------------------------------------------\n",
        "dataloader = trainer.get_train_dataloader()\n",
        "batch = next(iter(dataloader))\n",
        "\n",
        "print(\"=\" * 60)\n",
        "print(\"ВХОДНЫЕ ТЕКСТЫ (декодированные):\")\n",
        "for i in range(len(batch[\"input_ids\"])):\n",
        "    print(f\"\\nПример {i+1}:\")\n",
        "    print(tokenizer.decode(batch[\"input_ids\"][i], skip_special_tokens=False))\n",
        "\n",
        "print(\"\\n\" + \"=\" * 60)\n",
        "print(\"МАСКИРОВАННЫЕ LABELS (первые 50 токенов):\")\n",
        "for i in range(len(batch[\"labels\"])):\n",
        "    labels_list = batch[\"labels\"][i].tolist()\n",
        "    readable = [\"[MASK]\" if x == -100 else str(x) for x in labels_list[:50]]\n",
        "    print(f\"\\nПример {i+1}:\")\n",
        "    print(\" \".join(readable))\n",
        "\n",
        "print(\"\\n\" + \"=\" * 60)\n",
        "print(\"ЧТО МОДЕЛЬ БУДЕТ ПРЕДСКАЗЫВАТЬ (ответ ассистента):\")\n",
        "for i in range(len(batch[\"labels\"])):\n",
        "    mask = batch[\"labels\"][i] != -100\n",
        "    answer_tokens = batch[\"input_ids\"][i][mask]\n",
        "    print(f\"\\nПример {i+1}:\")\n",
        "    print(tokenizer.decode(answer_tokens, skip_special_tokens=False))"
      ],
      "metadata": {
        "id": "h9p0PFdVK72H"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "matHHdvUNOIv"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}